title: RubExp

url: https://ar2em1s.github.io
baseurl: /rubexp

plugins:
  - jekyll-sitemap

exclude:
  - package.json
  - tailwind.config.js
  - yarn.lock
  - assets/css
  - assets/js
  - build/index.css
  - README.md
  - LICENCE.txt
